sudo: true
merge_mode: replace   # for custom builds
language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      name: osx
    - os: linux
      dist: bionic
      name: bionic linux, python3.6
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.6-dev
            - python3-pip
            - python3-setuptools
    - os: linux
      dist: bionic
      name: bionic linux, python3.7
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.7-dev
            - python3-pip
            - python3-setuptools
    - os: linux
      dist: bionic
      name: bionic linux, python3.8
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.8-dev
            - python3-pip
            - python3-setuptools

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libboost1.65-all-dev ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then brew reinstall openssl                    ; fi
  - git clone https://github.com/named-data/ndn-cxx.git
  - git checkout -b ndn-cxx-0.7.0
  - cd ndn-cxx
  - ./waf configure
  - ./waf
  - sudo ./waf install && cd ..
  - git clone https://github.com/named-data/NFD.git
  - git checkout -b NFD-0.7.0
  - cd NFD && ./waf configure --without-libpcap --without-websocket && ./waf && sudo ./waf install && cd ..
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ldconfig ; fi
  - sudo nfd start -c /usr/local/etc/ndn/nfd.conf.sample &
install:
  - pip3 install pytest
  - pip3 install .
script:
  - pytest